### ISSUE TITLE
Unable to install latest version of Gummy

### ISSUE THREAD

**Issue by JDMorris81** [Fushko/gummy#11]
When attempting to install the latest version via DEB file, I'm getting a message stating, "Unable to install gummy: The following packages have unmet dependencies". I'm running Zorin OS which is an Ubuntu/Gnome based distro. Version 1 of Gummy ran just fine and I was able to reinstall it after this issue with version 2. Appreciate your work on this, also will there be a GUI version? I have Gammy for Windows and find it's easier for me to work with. Thanks

**Comment by JDMorris81** [comment]
![Screenshot from 2022-04-24 02-25-05](https://user-images.githubusercontent.com/72824463/164997898-e2de1d17-7f53-4372-ab05-9adf953e131f.png)

**Comment by Fushko** [comment]
That error fails to actually show the unmet dependency.

Could you try running `sudo apt install gummy_0.2_amd64.deb` in the terminal? It will probably show the error.

> will there be a GUI version?

Not planned at this time.

**Comment by JDMorris81** [comment]
Unable to locate package. I have the file in my Downloads directory.
![Screenshot from 2022-04-25 13-19-02](https://user-images.githubusercontent.com/72824463/165169207-81805c93-1b70-4496-abc5-14194fc8afda.png)

**Comment by Fushko** [comment]
You need to `cd` in the directory where the package is located before running that command.

**Comment by JDMorris81** [comment]
Same thing 
![Screenshot from 2022-04-26 17-22-19](https://user-images.githubusercontent.com/72824463/165414011-92239150-28c7-4139-831a-d72b90924386.png)

**Comment by Fushko** [comment]
Try `sudo apt install ./gummy_0.2_amd64.deb`

**Comment by JDMorris81** [comment]
Here's what I got. 
![Screenshot from 2022-04-27 05-53-33](https://user-images.githubusercontent.com/72824463/165522829-6f3e2ced-610d-4803-b184-510dc999f529.png)

**Comment by Fushko** [comment]
I compiled the package on a libc version that is a bit too new for some distros. Same issue as #6. 

I'll see if I can provide a version with older requirements. in the meantime, if you feel adventurous you could try building from source as per the readme.

**Comment by JDMorris81** [comment]
>

**Comment by JDMorris81** [comment]
I'll stick with version 1 until then. Thanks anyway 🙂
