### ISSUE TITLE
No fade when using `--brt-auto-speed` lower than 1000

### ISSUE THREAD

**Issue by Henriquelay** [Fushko/gummy#13]
Firstly, thanks for the software. It's really neat. Loved gammy and this looks great, too.
On my AUR stable install, the brightness does not fades from the previous to the target brightness when using `--brt-auto-speed` lower than 1000, it just "hard cuts" from one to another.
I have also tried setting to another value and then re-running the command omitting the flag, to no avail.

Linux 5.17.5-arch1-2 x86_64

**Comment by Henriquelay** [comment]
On further testing, it actually only happens to values smaller than 1000, independent of `--brt-mode` 1 or 2

**Comment by Fushko** [comment]
Fixed in 0.3
