### ISSUE TITLE
nixpkgs package in the readme

### ISSUE THREAD

**Issue by IvarWithoutBones** [Fushko/gummy#16]
Hi! Thank you for your work on this project, it's been very useful for me.

A while ago I packaged it on nixpkgs, the package repository for NixOS. I was wondering if you would be interested in adding that to the packages section of the readme? 

Here is a link to our package: https://search.nixos.org/packages?channel=unstable&show=gummy&query=gummy. Note that this still shows version 0.2 as the update to 0.3 was merged just a moment ago, the site will reflect that in a few days.

For the udev rules to work on NixOS one would have to add the following line to their `configuration.nix`:
```nix
services.udev.packages = [ pkgs.gummy ];
```

**Comment by Fushko** [comment]
Done, thanks.
