### ISSUE TITLE
Gummy never Stops!!!

### ISSUE THREAD

**Issue by anwarsfaizul** [Fushko/gummy#17]
Even after stopping gummy, the effect stays. screen doesnot revert back to original color. Its like "Gummy Forever"

**Comment by Fushko** [comment]
To reset everything to default: `gummy -b 100 -t 6500`. 

It's not automatic on exit to avoid too much screen flashing when I'm testing; possibly I'll reconsider this behavior in the future.

**Comment by Fushko** [comment]
Fixed in 0.4
