### ISSUE TITLE
Screen keeps flickering when using the AUR version 

### ISSUE THREAD

**Issue by southernpoint** [Fushko/gummy#19]
I've got no idea why it's happening but no matter what settings I input the screen keeps flickering. Might it just be a 'me' issue?

**Comment by Fushko** [comment]
There are two AUR versions, which one?
Do you have another program running that modifies gamma state (e.g. Redshift)?

**Comment by southernpoint** [comment]
> There are two AUR versions, which one? Do you have another program running that modifies gamma state (e.g. Redshift)?

This [one](https://aur.archlinux.org/packages/gummy) .
Also I got gammy installed from the AUR but it wasn't running when I was running gummy.

**Comment by Fushko** [comment]
- Try 0.4, which includes a large number of improvements.
- Check if you have the `colord` daemon running in your system. Some distros ship with it and I used to have screen flickering issues with it.

**Comment by mi544** [comment]
@southernpoint gummy version 0.4.1 just made it to the [AUR](https://aur.archlinux.org/packages/gummy), feel free to try upgrading to see if the issue persists

**Comment by southernpoint** [comment]
> * Try 0.4, which includes a large number of improvements.
> 
>     * Check if you have the `colord` daemon running in your system. Some distros ship with it and I used to have screen flickering issues with it.



> @southernpoint gummy version 0.4.1 just made it to the [AUR](https://aur.archlinux.org/packages/gummy), feel free to try upgrading to see if the issue persists

Sorry for the late reply, it seems to be working now.
