### ISSUE TITLE
Short `gummy` documentation now available in `tldr`!

### ISSUE THREAD

**Issue by mi544** [Fushko/gummy#22]
This is not an issue, just sharing good news that the [`tldr-pages` project](https://github.com/tldr-pages/tldr) now includes a short documentation page for `gummy`! This should help new `gummy` users with a `tldr` client to get started faster, and for potential users to see some of the common functionality it provides.
The page can be updated in the future in case some of the syntax changes or new options are added. Some common but complex command examples can additionally be added to that page in the future. 

https://github.com/tldr-pages/tldr/pull/9900

Fetching a tldr page for gummy now displays the following:
```
$ tldr gummy

  Screen brightness/temperature manager for Linux/X11.
  More information: <https://github.com/Fushko/gummy>.

  Set the screen temperature to 3000K:

      gummy --temperature 3000

  Set the screen backlight to 50%:

      gummy --backlight 50

  Set the screen pixel brightness to 45%:

      gummy --brightness 45

  Increase current screen pixel brightness by 10%:

      gummy --brightness +10

  Decrease current screen pixel brightness by 10%:

      gummy --brightness -10

  Set the temperature and pixel brightness for the second screen:

      gummy --screen 1 --temperature 3800 --brightness 65
```

**Comment by Fushko** [comment]
Great stuff! Thanks.
