### ISSUE TITLE
Error when starting gummy

### ISSUE THREAD

**Issue by pujvz** [Fushko/gummy#23]
Hi, the previous version was working great. After upgrading, I am receiving this error right after `gummy start`. 

```
➜  ~ gummy start
➜  ~ terminate called after throwing an instance of 'std::runtime_error'
  what():  [x11] DP-4 edid is 384 bytes

➜  ~ gummy status
not running
```

**Comment by Fushko** [comment]
Hi, thanks for the feedback.

This is caused by an incorrect assumption on my part, as newer displays can have a longer identification data than usual. 

I'll work on a fix. Where did you install gummy from?

**Comment by Fushko** [comment]
Hotfix 0.5.1 should fix this. Let me know if you're still having trouble.

**Comment by pujvz** [comment]
Hotfix is working so far and gummy is starting without error :). Installed from aur. Thanks!

**Comment by Fushko** [comment]
Awesome :-) you're welcome.
