### ISSUE TITLE
Sending mulitiple brightness commands causes gummy to hang

### ISSUE THREAD

**Issue by pujvz** [Fushko/gummy#25]
I have several hotkeys to send commands such as `gummy -b 50 -p 100`, `gummy -b 20 -p 100`, `gummy -b 0 -p 50`, etc. If I accidentally send 2 or more of these commands in less than a second, then gummy hangs. I have to kill both gummy and gummyd before `gummy start` in order to make gummy function again. Please let me know if you are able to reproduce.

**Comment by Fushko** [comment]
Hi, thanks for the heads-up.

Multiple commands in quick succession certainly need better handling. I've been able to produce a bunch of errors within commands sent on a loop simultaneously from two different terminals. However, so far the daemon simply ignores these commands without crashing on my end.

Not sure about the hanging yet. I'll probably replace the current system with a better solution, which should hopefully take care of it.

**Comment by Splarkszter** [comment]
Yup, i get this same problem. I have hotkeys for brightness and yeah if i do it too fast it does hang. So i have to restart the PC to solve it (unless there is a better way).

**Comment by pujvz** [comment]
Try to kill gummy and gummyd, then start gummy again. Should be no need to reboot.

**Comment by Splarkszter** [comment]
> Try to kill gummy and gummyd, then start gummy again. Should be no need to reboot.

Yeah i tried putting the name but it said it needs the process ID, so oh well restart only takes at most 20 seconds.

**Comment by Fushko** [comment]
Solved in master branch. 

This fix uses file locking, which can be a bit slow when sending commands too fast (e.g. pressing down a shortcut). 

Still better than nothing, but I'll look into adding a proper message queue for the next release if it doesn't take too long.

**Comment by Splarkszter** [comment]
Thanks for your work!!!

For now i use a workaround that is going in steps of 50 alongside the key for steps of 10. Which has worked very well :)

**Comment by Fushko** [comment]
Should be fixed in 0.5.3. 

I did not find a proper way to prevent slowdowns when holding down a shortcut yet (well, apart from slowing down the repeat rate in the DE settings, but that's cheating). This fix should suffice in the meantime.

**Comment by Splarkszter** [comment]
Will, test. Thanks!

**Comment by Splarkszter** [comment]
It seems to work perfectly. Even when holding down the shortcut key.

OS: Linux Mint 21.1

**Comment by Fushko** [comment]
Awesome, thanks.
