### ISSUE TITLE
Installation dependencies of the .deb package are too early.

### ISSUE THREAD

**Issue by datalot-369** [Fushko/gummy#27]
1. I'm using MX Linux 21.3, based on Debian 11.6 Bullseye.
2. You can see below that I need `libc6 v2.34`, but Bullseye has `v2.31`.
3. Installing a different version requires a system update to the testing edition of the upcoming Debian 12 version (MX Linux 23-beta1, in my case), which is nonsense for this app.
4. For instance, Ubuntu 20.04 LTS users would face this same issue (`libc6 v2.31`), having to update to 22.04 LTS (`libc6 2.35`).
5. Is not it an unnecessarily high requirement?

```
Installing the selected package please authenticate

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'gummy' instead of '/home/datalot/Downloads/gummy_0.5.2_amd64.deb'

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gummy : Depends: libc6 (>= 2.34) but 2.31-13+deb11u6 is to be installed
         Depends: libddcutil4 (>= 1.2.2) but it is not installable
         Depends: libsdbus-c++1 (>= 1.1.0) but it is not installable
         Depends: libstdc++6 (>= 12) but 10.2.1-6 is to be installed
E: Unable to correct problems, you have held broken packages.

Press any key to close
```

**Comment by Fushko** [comment]
> Is not it an unnecessarily high requirement?

I must admit I haven't given the DEB package much consideration, beyond making it work on my system (which happens to be based on Ubuntu 22.04 at this time). My primary focus is on programming, so I'd rather allocate my time in that regard.

I encourage you to ask some DEB packager or give it a shot yourself. I would happily put a link to a better DEB package on the README.

**Comment by datalot-369** [comment]
I'll proceed to close this issue as Debian 12 Bookworm has been released and MX Linux has finally launched the so expected 23 version... It's not actually a reason to close it, but well... LTS versions are not meant to provide core updates to their users. (speaking about Ubuntu 20.04, which was released 3 years ago).

Consideration on backward compatibility should be taken, however.
