### ISSUE TITLE
Can you eloborate pixel brightness vs backlight brightness?

### ISSUE THREAD

**Issue by toprak** [Fushko/gummy#30]
Hi, I want to use gummy to relax my eyes because my eyes often burn while using the computer, but I don't know which values to lower, now I will lower the temperature to be like a blue light filter, yes, but I don't understand the difference between the other two. Thanks

**Comment by Fushko** [comment]
Hi, backlight brightness is the amount of light emitted by the light bulb behind your screen. This is what causes the most eye strain. Ideally it should match the brightness level of your room.

Pixel brightness is a filter that dims the pixel's RGB values in a similiar fashion to the blue light filter. I would recommend only using it if backlight control doesn´t work on a screen. But feel free to experiment.
