### ISSUE TITLE
Error when running `gummy start`

### ISSUE THREAD

**Issue by hankertrix** [Fushko/gummy#32]
Hi, I got the error shown below when running `gummy start`.

![image](https://github.com/Fushko/gummy/assets/91734413/81cdc3f4-d812-46e4-9133-d1eaefee87c3)

This happened after upgrading the packages listed below. I am using EndeavourOS 64-bit with kernel `6.5.9-arch2-1` and i3 window manager.

```
upgraded amd-ucode (20230804.7be2766d-2 -> 20230918.3672ccab-1)
upgraded gpgme (1.23.0-1 -> 1.23.1-1)
upgraded libyuv (r2322+3aebf69d-1 -> r2426+464c51a0-1)
upgraded libavif (1.0.1-3 -> 1.0.1-4)
upgraded linux-firmware-whence (20230804.7be2766d-2 -> 20230918.3672ccab-1)
upgraded linux-firmware (20230804.7be2766d-2 -> 20230918.3672ccab-1)
```

Below is the output of `ldconfig -p | grep libdd`:

![image](https://github.com/Fushko/gummy/assets/91734413/90ce7a32-66a6-412f-bb25-c08dedce02cb)

`libddcutil.so.4` is not present at all.

<br>
<hr>
<br>

While writing this issue, I decided to uninstall gummy and clean-build the package. Now gummy won't build at all:

![image](https://github.com/Fushko/gummy/assets/91734413/e20db2a6-c840-4e5d-9745-b363bf33c1a1)

![image](https://github.com/Fushko/gummy/assets/91734413/2e23dcf2-4afb-4139-ad6a-50b2e09f05a2)

The above two pictures are where the build process encountered errors. The rest of the build process was without errors.

**Comment by Fushko** [comment]
Hi, it appears there is a new release of ddcutil that removes some functions from the API. I'll proceed to remove them. Thanks for the heads up.

**Comment by Fushko** [comment]
Should be fixed now. Feel free to let me know if you're still having trouble.

**Comment by hankertrix** [comment]
Yeap it's fixed. Thank you so much! I will close the issue.
